
name: Compile mvn and npm and deploy with docker

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  mvn-compile:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
        cache: maven
    - name: mvn compile
      run: sudo mvn -f /home/ubuntu/actions-runner/_work/noroff-assignment3/noroff-assignment3/MoviesAPI compile
  mvn-test:
    runs-on: self-hosted
    needs: mvn-compile
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
        cache: maven
    - name: mvn test
      run: sudo mvn -f /home/ubuntu/actions-runner/_work/noroff-assignment3/noroff-assignment3/MoviesAPI test
  mvn-build:
    needs: [mvn-compile, mvn-test]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
        cache: maven
    - name: mvn build jar file
      run: sudo mvn -f /home/ubuntu/actions-runner/_work/noroff-assignment3/noroff-assignment3/MoviesAPI clean install
