
name: Compile mvn and npm and deploy with docker

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  mvn-compile:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        cache: maven
    - name: mvn compile
      run: sudo mvn -f /home/ubuntu/repos/MoviesAPI compile
  mvn-test:
    runs-on: self-hosted
    needs: mvn-compile
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        cache: maven
    - name: mvn test
      run: sudo mvn -f /home/ubuntu/repos/MoviesAPI test
  mvn-build:
    needs: [mvn-compile, mvn-test]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        cache: maven
    - name: mvn build jar file
      run: sudo mvn -f /home/ubuntu/repos/MoviesAPI clean install

  docker-compose:
    needs: mvn-build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: docker stop back
      run: docker stop movies_backend_1
    - name: docker stop db
      run: docker stop movies_db_1
    - name: docker rm back
      run: docker rm movies_backend_1
    - name: docker rm db
      run: docker rm movies_db_1
    - name: docker-compose
      run: docker-compose -f /home/ubuntu/repos/MoviesAPI/compose.yaml -p movies up -d
